### ISSUE TITLE
Why there's no await when calling find methods?

### ISSUE THREAD

**Issue by OfirD1** [hagopj13/node-express-boilerplate#110]
(It's not an issue, just a question)

Why there's no `await`  when calling `find` methods?

for example:

```
const getUserById = async (id) => {
  return User.findById(id);         <-- no await
};
```
or: 
```
const getUserByEmail = async (email) => {
  return User.findOne({ email });   <-- no await
};
```

I thought that maybe the rationale was: "no await before mongoose methods", but it can't be that, because there is an `await` before other mongoose methods, such as `create`, for example:

```
const createUser = async (userBody) => {
  if (await User.isEmailTaken(userBody.email)) {
    throw new ApiError(httpStatus.BAD_REQUEST, 'Email already taken');
  }
  const user = await User.create(userBody);    <-- has await
  return user;
};
```

**Comment by trasherdk** [comment]
Returning a promise makes the function chainable.
```js
getUserByEmail ('john.doe@example.com')
  .then()
  .catch()
```

**Comment by Sicria** [comment]
This might also be an interesting read to understand why you might not want to call await before returning. https://eslint.org/docs/rules/no-return-await

**Comment by turanibrahim** [comment]
> Returning a promise makes the function chainable.
> ```js
> getUserByEmail ('john.doe@example.com')
>   .then()
>   .catch()
> ```

Also it can be use in try-catch block with async keyword like I shown below

 ```js
try {
  const result = await getUserByEmail ('john.doe@example.com');
} catch(err) {
// You can catch the error that returned from Promise(getResultByEmail)
}

```

**Comment by trasherdk** [comment]
@turanibrahim That will work too :smiley: but consult link referenced in [@Sicria's reply](https://github.com/hagopj13/node-express-boilerplate/issues/110#issuecomment-833440033).

**Comment by OfirD1** [comment]
It's unfortunate that this issue was closed, as my question wasn't really answered. The answers here justify what happens in `getUserById` (which has no `await`), but then - by the same rationale - shouldn't the `await` in `createUser` (which has an `await`) be removed?
