### ISSUE TITLE
auth middleware usage

### ISSUE THREAD

**Issue by am2222** [hagopj13/node-express-boilerplate#113]
Hello,
I checked this middleware and it seems straightfoward. However I wanted to see how we can achieve the following authentication structure:
lets say we have this route:
```router.patch('/users', auth('manageUsers'), userController.updateUser);```
How we can only make a user use it if they are only updating their own profile? If we set this rule clearly users who have access to `manageUsers` can update eachother's profiles. But we want a user only be able to update their own profile. Maybe we should use validations?

**Comment by bryan-gc** [comment]
I didn't use the whole template, but the jwt should be in the request object. So you should extract the id from that jwt and check if the user he is updating is the same that he has in the jwt.

**Comment by hagopj13** [comment]
@am2222 this feature is already supported if the user is trying to fetch/update/delete its own profile. Check here: https://github.com/hagopj13/node-express-boilerplate/blob/1610883faa8cbe8801a6287cda142d7c37c59426/src/middlewares/auth.js#L15

**Comment by yasamnoya** [comment]
Hi, @hagopj13 

I'm just wondering what you would recommend if I want users can only modify/delete its own posts, where posts are objects stored in another document and has a property called `userId`, which represent the owners of the posts. 
The laziest solution is to check if `userId` and `req.user._id` are matched in `posts.services.js`. But I believe there is a better solution.

Thanks anyway.
