### ISSUE TITLE
Validate middleware didn't throw all error messages

### ISSUE THREAD

**Issue by bwyx** [hagopj13/node-express-boilerplate#124]
hi @hagopj13, first of all, thank you for this boilerplate, it's very useful for my learning path.

I think I found an unintended contradictive statement

Joi compiled schema without `abortEarly` option set to `false` at [validate.js#L11](https://github.com/hagopj13/node-express-boilerplate/blob/ca2341514487c0035a527e6283799a82bd6160c1/src/middlewares/validate.js#L11) :
```js
const { value, error } = Joi.compile(validSchema)
    .prefs({ errors: { label: 'key' } })
    .validate(object);
```
therefore Joi will not return all errors it finds, only the first one.

but, on next [line #14](https://github.com/hagopj13/node-express-boilerplate/blob/ca2341514487c0035a527e6283799a82bd6160c1/src/middlewares/validate.js#L14), `errorMessage` assigned from merged `error.details` which is always only one:
```js
const errorMessage = error.details.map((details) => details.message).join(', ');
```

is it supposed to be?

I'll gladly make a PR about this.
thank you. 😄

**Comment by vishnubhadoriya** [comment]
by default abortEarly is true so its stops validation on first value
in order to validate all you need to enable or set abortEarly : false

`const { value, error } = Joi.compile(validSchema)
    .prefs({ errors: { label: 'key' } })
    .validate(object, {
      abortEarly: false,
    });`

**Comment by hagopj13** [comment]
@bwyx thanks for the tip!

**Comment by bwyx** [comment]
@vishnubhadoriya that's my point
