### ISSUE TITLE
error: Error: Not found

### ISSUE THREAD

**Issue by ThannsokKhen** [hagopj13/node-express-boilerplate#127]
After running `yarn dev` and go to [http://localhost:3000/](url)

error: GET /sw.js 404 - 16.433 ms - message: Not found

**Comment by FoushWare** [comment]
Make sure you use these routes in proper way ⇒ routes are POST type not GET
try using postman and make sure the request content type is JSON 
![postman](https://user-images.githubusercontent.com/18531447/122068552-cb369b80-cdf4-11eb-9848-4db17c657f04.png)
`

**Comment by rahulvramesh** [comment]
same happening for me , but in swagger ui
