### ISSUE TITLE
Q: Howto first login as admin

### ISSUE THREAD

**Issue by KingKnecht** [hagopj13/node-express-boilerplate#223]
Sorry, I'm a total noob with auth and stuff.

How would I login/authenticate as admin for the first time?
Swagger UI says, only admin is allowed to add users. 

![image](https://user-images.githubusercontent.com/4339172/194918935-43565c3e-871d-4646-adad-0cf5fa016972.png)

I don't even have an admin user.

Thx

**Comment by joramatveev** [comment]
> Sorry, I'm a total noob with auth and stuff.
> 
> How would I login/authenticate as admin for the first time? Swagger UI says, only admin is allowed to add users.
> 
> ![image](https://user-images.githubusercontent.com/4339172/194918935-43565c3e-871d-4646-adad-0cf5fa016972.png)
> 
> I don't even have an admin user.
> 
> Thx

Hi!
Run this command in console: 
```
mongosh --eval 'db.users.insertOne({ "name": "Administrator", "email": "admin@admin.com", "password": "$2b$08$XNx4snBSEOwQIRT.3e9RGOW0NzZbdSP7dffZAQNBax3H6qXw9LVMS", "role": "administrator", "isEmailVerified": true });' YOUR_DB
```
**login:** admin@admin.com
**pwd:** Pool12345
