### ISSUE TITLE
Check If Authenticated In Middleware

### ISSUE THREAD

**Issue by omerfdmrl** [hagopj13/node-express-boilerplate#233]
Hi. I want to check if authenticated in new middleware like that;

new-plugin.js
```
module.exports = async(req, res, next) => {
    if (req.user) { ... }
    next();
};
```

In app.js I'm using right before then `v1 api routes`. `Auth` middleware calling after that middleware. How can I fix that?

**Comment by alibabayev0** [comment]
Hi Ömer, please may you describe more detailed?
