### ISSUE TITLE
How to attach debuger (Visual Studio Code) ?

### ISSUE THREAD

**Issue by Shidooo** [hagopj13/node-express-boilerplate#67]
Hello,

I was unable to attach the visual studio code debugger to the project. 

How can I do this?

Best regards,

_Very nice project, thank you for your work_

**Comment by hagopj13** [comment]
Hi @Shidooo, have you tried this: https://itnext.io/the-absolute-easiest-way-to-debug-node-js-with-vscode-2e02ef5b1bad ?

**Comment by Shidooo** [comment]
Looks like it's good,

Thanks for helping !
