### ISSUE TITLE
VS Code Remote Containers

### ISSUE THREAD

**Issue by adrian-filipow** [hagopj13/node-express-boilerplate#70]
Hey, first of all thank you for this boilerplate. It's amazing.

This might not be a thing for everyone, but I found an extension for VS Code that takes the development process with docker to the next level. [Documentation: Remote Containers](https://github.com/Microsoft/VSCode-docs/blob/master/docs/remote/containers.md)

The docs are straight forward but to summarize some key features:

- it creates a devcontainer.json file that tells VS Code how to create the dev container
  - the container is able to use the full feature set of VS Code
  - it has a lot of default templates to get started quickly
  - ability to specify default VS Code extensions and individual configurations that will be used in the container dev environment independently from your local VS Code configuration
  - ability to use VS Code the same way as always, but beeing inside the container
  - is able to use your local git config inside the dev container
  - much more cool stuff...
- it can use a seperate dockerfile
  - ability to create a dockerfile for development combining all required services e.g. node and mongo into a single image (this comes in handy when your project starts to grow and requires a lot of additional services like redis etc. )

Overall benefits:

- requires less local dependencies (everything is in a single dev container)
- completely isolated from your local dev environment
- all required services are accessable from a single terminal
- less interference with your existing VS Code extensions and configurations because they can be set on a project base
- ability to ensure everyone working on the project has the same 'perfect' ide setup
- it's powerful to have and only requires 2 files

Any opinions?

**Comment by hagopj13** [comment]
Hi @adrian-filipow, this looks nice. Seems like there isn't the need to add anything in the project to use this extension. Am I right? Except maybe some explanation in the README to inform developers about the existence of such a tool.
