### ISSUE TITLE
email is required

### ISSUE THREAD

**Issue by iamsajithsasi** [hagopj13/node-express-boilerplate#72]
I tried to post an request to /v1/auth/register but it error as - message: "email" is required. However, I have given an valid email eventhough its getting rejected. why is this happening ? please let know your thoughts on this. Thanks

{
  "name": "admin",
  "email": "admin@gmail.com",
  "password": "password!!"
}

**Comment by hagopj13** [comment]
@iamsajithsasi your request body looks good, so I find no reason why the request is failing. Where are you executing the request? Are you using application/json as the content type?

**Comment by iamsajithsasi** [comment]
hey @hagopj13 Thanks for the response. The package was not installed correctly. I have re-downloaded and it ran perfect. Great work !!!
