### ISSUE TITLE
Slug generate 

### ISSUE THREAD

**Issue by kvlknctk** [hagopj13/node-express-boilerplate#79]
Hi, 
I want to generate slug on create model entry. There is have some plugins for this. 
https://github.com/talha-asad/mongoose-url-slugs
https://github.com/ladjs/mongoose-slug-plugin

I can use but I am searching native and simple method without plugin. Is this possible? 

Thank you.

**Comment by hagopj13** [comment]
@kvlknctk you can create your own plugin, where you would attach your custom slug code to the pre `validate` hook.

**Comment by peter-palmer** [comment]
I personally use Slugify. Check it here: https://www.npmjs.com/package/slugify

And then I add it in to any model like this:

```
exampleSchema.pre('validate', async function () {
  this.slug = slugify(this.title, { lower: true })
})
```
