### ISSUE TITLE
Mongos timestamps absent from res json

### ISSUE THREAD

**Issue by tevon456** [hagopj13/node-express-boilerplate#80]
In the mongo models, I enabled the ```{timestamps: true}``` however when logging out the response the updatedAt and createdAt values are present but never come across in the JSON response to the client I'm not sure why this is also true for paginated responses as well.

**Comment by hagopj13** [comment]
Hi @tevon456, that is because of the `toJSON` plugin that is being used with the model (for instance, `userSchema.plugin(toJSON);`). You can remove that, or modify the plugin itself to fit your needs.

**Comment by tevon456** [comment]
Hey, @hagopj13 I just found it thanks for the quick response this solved my issue.
