### ISSUE TITLE
Typescript version of the boilerplate

### ISSUE THREAD

**Issue by abdurrahmanarikan** [hagopj13/node-express-boilerplate#85]
Thanks for creating this repo. It's helpful to fire a server without spending too much time. It would be nicer to have the same repo for the typescript(I know it already supports it but could be good not to spend time converting it from javascript). 

Anyway, Good Job!

**Comment by hagopj13** [comment]
Hi @abdurrahmanarikan thanks for the complements and the suggestion. I do plan to create an enhanced version of the boilerplate in TypeScript. Just need to find the time for it ;)

**Comment by knutole** [comment]
That would indeed be amazing! Any ETA for that? Or any way you need help?

**Comment by jahead** [comment]
Would be interested in this as well

**Comment by Tasin5541** [comment]
@hagopj13 any update on the typescript version?

**Comment by ngthuongdoan** [comment]
https://github.com/ngthuongdoan/node-express-boilerplate
I'm currently working on this, have some issues of types left to check
